spring:
    application:
        name: skeleton-ms
    profiles:
        include: logger

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus,metrics