kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["configmaps"]
    resourceNames: ["global-config"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "service.serviceAccountName" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "service.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
