apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.agent.enabled }}
    - port: { { .Values.service.agent.port } }
      targetPort: agent
      protocol: TCP
      name: agent
      {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
